function agent_log_debug(debug_cfg, hypothesis_id, location, message, data)
try
    ts_ms = round((now - datenum(1970,1,1,0,0,0)) * 86400000);
    payload = struct( ...
        'sessionId', debug_cfg.session_id, ...
        'runId', debug_cfg.run_id, ...
        'hypothesisId', hypothesis_id, ...
        'location', location, ...
        'message', message, ...
        'data', data, ...
        'timestamp', ts_ms);

    if exist('jsonencode', 'builtin') || exist('jsonencode', 'file')
        line = jsonencode(payload);
    else
        line = sprintf(['{"sessionId":"%s","runId":"%s","hypothesisId":"%s",' ...
            '"location":"%s","message":"%s","data":"jsonencode_unavailable","timestamp":%.0f}'], ...
            escape_json(char(debug_cfg.session_id)), ...
            escape_json(char(debug_cfg.run_id)), ...
            escape_json(char(hypothesis_id)), ...
            escape_json(char(location)), ...
            escape_json(char(message)), ...
            ts_ms);
    end

    fid = fopen(debug_cfg.log_path, 'a');
    if fid ~= -1
        fprintf(fid, '%s\n', line);
        fclose(fid);
    end
catch
    % Intentionally ignore logging failures to avoid changing script behavior.
end
end

function out = escape_json(in)
out = strrep(in, '\', '\\');
out = strrep(out, '"', '\"');
end
